language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=sphinxcontrib.multilatex
after_success: coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  user:
    secure: k2EvgTeHVBFrKo0DFvgGl/iCDJOH/5a7wFrevqffik9SJnGxUCqGfbcrQjH5AW9yaozIpoKkHcEIh4VDrR/ICXRa2SjSrvk10HFvJZuBghX0soCP5aqLjM4ceMCOaCVwPCSehY8jNg01V3cXYM3d3o6JwdMK1kXSLzDSqqmATy3mNGZ07UkRFHgy2N+ygPCsLaicWGNT4JvOuxPasoBKg1s9YmubS0NDfjWoYqBKd+mllmRWFNro+DIoMAAtDdy5bBb54OGSIjcSIrfzIQ2PbCUw6Pj4MkUF1wUkkvHNwFYKe2PNEmx0EWnkSqdRCCLNq9Vz9uVonrP2qCxjZMz+dG1yB6jsSiDVjR5hD4kNTkX1K0/DpzwWXuO154fdAkjOGF4ohQW46m1apzHMS4uLeczaYkEb6eEZLax/dEDql7Xvx1lHM/3fRmZ5Nz3voh6EDNknRKwnZrJG7bYsiLxYcshvC3lPB6Xf51u6IFfqTcdm6CU0k2qQZxhaX50iBArGwipet+GEsLMjOkSYi29LtiSOrDrpa4E0ML7oArjl5Bfqc3ITfb7uelRv8ZPJtH+k55EDBNpN+k2yS9V33FK83wP0uesGZFiroB9NHM9KrYCsSokup2YFr5IoUMkH8D5uNK6kp3jYi9IvAMiLIFgcKXo1dcjHbw+pS7T07CwwFgY=
  password:
    secure: EJneXvncnQ9t+HH/3ZLWRkXosFBZ7/GGrWZ2K/MmHgFBoI4PqbLy75MalOfUB/ooFymgf6exg9N+IdD77PslWf6h6kBqeCsAIrTt7o2cloHicrRu/2v0LG6bVEgU6onMg0S77L0C+kUItEOKiq+DsOJU/+ciF2i9x6leM8ij8whthundlyQEZW8C7unv6OFR3iuuEOaOIZSQYZ3eFpBAOjU+ycTwsO7v/cKWQdMmYy3JDHK61twL2/Sq2wpoGNsMaD+lRO4P9g5Ql218rpxjPBxic/7oGz/44GaDPv/4RZJvwl0CXrLwc6K46lu0KhUBmLZk8MMUwB2xu/D59b7m12QYPg58ETi8DsED+GdVL63NVumHYrtJ8XDuzReCnMThGDlAxDC4Kg9IMvi/iQuTCQ9zBKrgxIgBC8ZJ6InBK173FnfDpuGrqMTNEogEEfwkkNnxRWQpgmg35wDObbYoyQOWs0Q1SnxvbL+0zh5gdMDw4EU3MEsRKXFSFb1i0TswNuAPw49bicQue/7g7MlE0XLuoSBIo5LVpuzNib3641ZqxsUp4Xra7Rtly7YnX12Lpfrb8oiBDhQuOdJYjwGpEmNmHwRO67Ce2i7tQH9Yo6ryuxQFMDHFZHWB7TMiTZdXI1Ozl9H/4cthlmDWwV6xrGMH34kF4MOXU2IodZ1ML9I=
